name: Build and deploy Azure Web App
on:
  push:
    branches: [main]
#   pull_request:
#     branches: [main]
  workflow_dispatch:
  
jobs:
    build_web_app:
      name: 🧪 Build Web App
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Configure App Settings
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["Tailspin.SpaceGame.Web/appsettings.json"]'
        env:
          LEADERBOARD_API_URL: https://${{env.API_APP_NAME}}.azurewebsites.net/api/Leaderboard
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.Web
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.Web
      
      - name: Publish
        run: dotnet publish --no-restore -c Release
        working-directory: ./Tailspin.SpaceGame.Web
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: spacegameweb
          path: ./Tailspin.SpaceGame.Web/bin/Release/netcoreapp3.1/publish/

    deploy:
      name: 🚀 Deploy
      runs-on: self-hosted
      environment: deploy
      needs: build_web_app

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: spacegameweb

        - name: Azure WebApp
          uses: Azure/webapps-deploy@v2
          with:
            app-name: mytailspindemo
            package: . 
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
